import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph:{
    title:'Create Meme',
    description:'A meme creation frame app',
    images:[`${process.env.NEXT_PUBLIC || 'http:://localhost:3000'}/textyeat.png`],
=======
  title: 'Create Meme',
  description: 'A meme creation frame app',
  openGraph: {
    title: 'Create Meme',
    description: 'A meme creation frame app',
    images: [`${process.env.VERCEL_URL || 'http://localhost:3000'}/textyeat.png`],
>>>>>>> 39181dcc69e5c852b4695a7998fd22af78fc8fee
  },
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
